In [ ]:
from google.colab import auth
auth.authenticate_user()

In [ ]:
import os
os.makedirs("/content/nutrition5k_subset/images", exist_ok=True)

In [ ]:
import subprocess

# Dish folder name
dish_folder = "dish_1556572657"

# Remote path in Google Cloud
remote_path = f"gs://nutrition5k_dataset/nutrition5k_dataset/imagery/realsense_overhead/{dish_folder}/rgb.png"

# Local path in Colab
local_path = f"/content/nutrition5k_subset/images/{dish_folder}_rgb.png"

# Download the RGB image
subprocess.run(f"gsutil cp {remote_path} {local_path}", shell=True)

CompletedProcess(args='gsutil cp gs://nutrition5k_dataset/nutrition5k_dataset/imagery/realsense_overhead/dish_1556572657/rgb.png /content/nutrition5k_subset/images/dish_1556572657_rgb.png', returncode=0)

In [ ]:
# ===============================
# Step 1: Authenticate Google Cloud
# ===============================
from google.colab import auth
auth.authenticate_user()

import os
import subprocess

# ===============================
# Step 2: Setup local directories
# ===============================
DATA_DIR = "/content/nutrition5k_subset"
IMAGE_DIR = os.path.join(DATA_DIR, "images")
os.makedirs(IMAGE_DIR, exist_ok=True)

# ===============================
# Step 3: Configure dishes to download
# ===============================
# Replace with dish IDs from your Google Cloud bucket
dish_folders = [
    "dish_1556572657", "dish_1551225541", "dish_1551225542",
    # add more dish IDs here
]

MAX_IMAGES = 2000
count = 0

# ===============================
# Step 4: Loop and download images
# ===============================
for dish in dish_folders:
    if count >= MAX_IMAGES:
        break

    # The RGB image path in the bucket
    remote_rgb = f"gs://nutrition5k_dataset/nutrition5k_dataset/imagery/realsense_overhead/{dish}/rgb.png"

    # Local path in Colab
    local_rgb = os.path.join(IMAGE_DIR, f"{dish}_rgb.png")

    # Download RGB using gsutil
    result = subprocess.run(f"gsutil cp {remote_rgb} {local_rgb}", shell=True)

    if result.returncode == 0:
        count += 1

    if count % 50 == 0:
        print(f"{count} images downloaded...")

print(f"Done! Total images downloaded: {count}")

Done! Total images downloaded: 1

In [ ]:
# Step 1: Authenticate Google Cloud
from google.colab import auth
auth.authenticate_user()

import os
import subprocess
from PIL import Image
import glob

# Step 2: Setup local directories
DATA_DIR = "/content/nutrition5k_subset"
IMAGE_DIR = os.path.join(DATA_DIR, "images")
os.makedirs(IMAGE_DIR, exist_ok=True)

# Step 3: Set constants
MAX_IMAGES = 2000
count = 0

# Bucket base path for dish folders
bucket_base_path = "gs://nutrition5k_dataset/nutrition5k_dataset/imagery/realsense_overhead/"

# Step 4: Get all dish folders
dish_folders = subprocess.check_output(f"gsutil ls {bucket_base_path}", shell=True).decode().splitlines()

print(f"Found {len(dish_folders)} dish folders.")

# Step 5: Loop over dish folders and download rgb.png from each
for folder in dish_folders:
    if count >= MAX_IMAGES:
        break

    # Compose remote path to rgb.png
    remote_rgb_path = os.path.join(folder, "rgb.png")

    # Extract folder name, e.g. dish_1556572657
    folder_name = folder.rstrip('/').split('/')[-1]

    # Local file path to save rgb image
    local_rgb_path = os.path.join(IMAGE_DIR, f"{folder_name}_rgb.png")

    # Download rgb.png from this dish folder
    result = subprocess.run(f"gsutil cp {remote_rgb_path} {local_rgb_path}", shell=True)

    if result.returncode == 0:
        count += 1
        if count % 50 == 0:
            print(f"{count} images downloaded...")
    else:
        print(f"Failed to download {remote_rgb_path}")

print(f"Download complete: {count} images downloaded.")

Found 3490 dish folders.
50 images downloaded...
100 images downloaded...
150 images downloaded...
200 images downloaded...
250 images downloaded...
300 images downloaded...
350 images downloaded...
400 images downloaded...
450 images downloaded...
500 images downloaded...
550 images downloaded...
600 images downloaded...
650 images downloaded...
700 images downloaded...
750 images downloaded...
800 images downloaded...
850 images downloaded...
900 images downloaded...
950 images downloaded...
1000 images downloaded...
1050 images downloaded...
1100 images downloaded...
1150 images downloaded...
1200 images downloaded...
1250 images downloaded...
1300 images downloaded...
1350 images downloaded...
1400 images downloaded...
1450 images downloaded...
1500 images downloaded...
1550 images downloaded...
1600 images downloaded...
1650 images downloaded...
1700 images downloaded...
1750 images downloaded...
1800 images downloaded...
1850 images downloaded...
1900 images downloaded...
1950 images downloaded...
2000 images downloaded...
Download complete: 2000 images downloaded.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!cp -r /content/nutrition5k_subset /content/drive/MyDrive/

In [ ]:
import os
import pandas as pd

# 1️⃣ Path where images were downloaded
IMAGE_DIR = "/content/nutrition5k_subset/images"

# 2️⃣ Get list of downloaded image filenames
image_files = os.listdir(IMAGE_DIR)

# 3️⃣ Extract dish IDs from filenames
downloaded_dish_ids = []

for file in image_files:
    if file.endswith(".png") or file.endswith(".jpg"):
        dish_id = file.replace("_rgb.png", "").replace("_rgb.jpg", "")
        downloaded_dish_ids.append(dish_id)

downloaded_dish_ids = set(downloaded_dish_ids)

print("Total downloaded dishes:", len(downloaded_dish_ids))

Total downloaded dishes: 2000

In [ ]:
!ls /content

dish_metadata_cafe1.csv  drive		     sample_data
dish_metadata_cafe2.csv  nutrition5k_subset

In [ ]:
import pandas as pd

# ===============================
# Step 1: Load both metadata files flexibly
# ===============================

meta1 = pd.read_csv(
    "/content/dish_metadata_cafe1.csv",
    header=None,
    engine="python",
    on_bad_lines='skip'  # Skip malformed lines
)

meta2 = pd.read_csv(
    "/content/dish_metadata_cafe2.csv",
    header=None,
    engine="python",
    on_bad_lines='skip'
)

# ===============================
# Step 2: Combine both cafes
# ===============================

metadata = pd.concat([meta1, meta2], ignore_index=True)
print("Total rows after combining:", len(metadata))

# ===============================
# Step 3: Extract only dish-level columns
# (Ignore ingredients; first 6 columns)
# ===============================

dish_level = metadata.iloc[:, 0:6]

dish_level.columns = [
    "dish_id",
    "total_calories",
    "total_mass",
    "total_fat",
    "total_carb",
    "total_protein"
]

print("\nCleaned Dish-Level Data:")
dish_level.head()

Total rows after combining: 4583

Cleaned Dish-Level Data:

,dish_id,total_calories,total_mass,total_fat,total_carb,total_protein
0,dish_1561662216,300.794281,193.0,12.387489,28.218290,18.633970
1,dish_1562688426,137.569992,88.0,8.256000,5.190000,10.297000
2,dish_1561662054,419.438782,292.0,23.838249,26.351543,25.910593
3,dish_1562008979,382.936646,290.0,22.224644,10.173570,35.345387
4,dish_1560455030,20.590000,103.0,0.148000,4.625000,0.956000

In [ ]:
# 2️⃣ Filter metadata for downloaded images
filtered_metadata = dish_level[dish_level['dish_id'].isin(downloaded_dish_ids)]

print("Rows after filtering:", len(filtered_metadata))
filtered_metadata.head()

# 3️⃣ Save the filtered CSV
filtered_metadata.to_csv("/content/nutrition5k_subset/labels_subset.csv", index=False)
print("labels_subset.csv created successfully!")

Rows after filtering: 1809
labels_subset.csv created successfully!

In [ ]:
# List of downloaded dish IDs not in CSV
missing_dishes = downloaded_dish_ids - set(dish_level['dish_id'])
print("Missing from metadata:", len(missing_dishes))
print(missing_dishes)

Missing from metadata: 191
{'dish_1561662926', 'dish_1562007817', 'dish_1562097673', 'dish_1562097001', 'dish_1562872498', 'dish_1560456348', 'dish_1561666897', 'dish_1560456370', 'dish_1562702469', 'dish_1561491210', 'dish_1561060703', 'dish_1560367333', 'dish_1562700593', 'dish_1562611680', 'dish_1561662562', 'dish_1562008517', 'dish_1560453412', 'dish_1562613403', 'dish_1560455442', 'dish_1562007904', 'dish_1561405411', 'dish_1561576767', 'dish_1562614980', 'dish_1561579845', 'dish_1560798928', 'dish_1561148021', 'dish_1562007866', 'dish_1563217804', 'dish_1562872746', 'dish_1562615388', 'dish_1561579867', 'dish_1562615360', 'dish_1560888930', 'dish_1562788601', 'dish_1563302447', 'dish_1562788816', 'dish_1560453174', 'dish_1560368506', 'dish_1561752563', 'dish_1562961650', 'dish_1560802149', 'dish_1560798960', 'dish_1561662948', 'dish_1561061687', 'dish_1561407312', 'dish_1560369294', 'dish_1561577219', 'dish_1561579706', 'dish_1560366460', 'dish_1562010440', 'dish_1561574479', 'dish_1561575033', 'dish_1562099134', 'dish_1562700957', 'dish_1562008813', 'dish_1560455421', 'dish_1562099157', 'dish_1562010929', 'dish_1563217993', 'dish_1560453328', 'dish_1560453380', 'dish_1561663855', 'dish_1560368990', 'dish_1562959190', 'dish_1561665452', 'dish_1562094931', 'dish_1561576320', 'dish_1562010418', 'dish_1562702892', 'dish_1562617492', 'dish_1561662869', 'dish_1560889061', 'dish_1562007842', 'dish_1563221054', 'dish_1562963517', 'dish_1560367296', 'dish_1561666875', 'dish_1561576707', 'dish_1560543605', 'dish_1561578441', 'dish_1561577947', 'dish_1561575068', 'dish_1562872470', 'dish_1560801883', 'dish_1563217968', 'dish_1563221157', 'dish_1562094730', 'dish_1560369313', 'dish_1562876732', 'dish_1561753477', 'dish_1561749061', 'dish_1561062237', 'dish_1562963704', 'dish_1561405912', 'dish_1561062286', 'dish_1561492228', 'dish_1562789328', 'dish_1561666923', 'dish_1562876756', 'dish_1561579933', 'dish_1562959570', 'dish_1561060642', 'dish_1561405934', 'dish_1560368570', 'dish_1563222850', 'dish_1562009182', 'dish_1562788794', 'dish_1562958809', 'dish_1560543755', 'dish_1561663914', 'dish_1559244649', 'dish_1562613974', 'dish_1562790855', 'dish_1562959547', 'dish_1560455263', 'dish_1562008549', 'dish_1562959599', 'dish_1562785369', 'dish_1561578417', 'dish_1562959799', 'dish_1561148481', 'dish_1561664013', 'dish_1560801041', 'dish_1562702132', 'dish_1561580406', 'dish_1560543625', 'dish_1560526552', 'dish_1561663891', 'dish_1562614952', 'dish_1561407283', 'dish_1563218031', 'dish_1560453356', 'dish_1562008842', 'dish_1560974009', 'dish_1561579673', 'dish_1561060613', 'dish_1560369403', 'dish_1562873028', 'dish_1561148042', 'dish_1560456326', 'dish_1562180157', 'dish_1563221086', 'dish_1561574623', 'dish_1561576794', 'dish_1562875320', 'dish_1561580431', 'dish_1562613376', 'dish_1561576074', 'dish_1562787817', 'dish_1560887480', 'dish_1562096608', 'dish_1560541760', 'dish_1562615128', 'dish_1562700568', 'dish_1561405034', 'dish_1562010394', 'dish_1561576051', 'dish_1562010865', 'dish_1561664042', 'dish_1561574848', 'dish_1561062320', 'dish_1563217939', 'dish_1561576737', 'dish_1561576978', 'dish_1562096973', 'dish_1562787848', 'dish_1562873838', 'dish_1561578461', 'dish_1560541793', 'dish_1559593794', 'dish_1559933834', 'dish_1561665065', 'dish_1561664061', 'dish_1560455399', 'dish_1560369008', 'dish_1561579902', 'dish_1562788845', 'dish_1561061123', 'dish_1562010891', 'dish_1562096633', 'dish_1560369421', 'dish_1563221640', 'dish_1561405008', 'dish_1560369146', 'dish_1561576954', 'dish_1561405389', 'dish_1563222830', 'dish_1561576680', 'dish_1560454562', 'dish_1561578394', 'dish_1562615153'}

In [ ]:
# Strip whitespaces just in case
dish_level['dish_id'] = dish_level['dish_id'].astype(str).str.strip()

# Convert downloaded IDs to strings and strip
downloaded_dish_ids = set([str(d).strip() for d in downloaded_dish_ids])

# Find missing dishes
missing_dishes = downloaded_dish_ids - set(dish_level['dish_id'])
print("Missing from metadata:", len(missing_dishes))
print(missing_dishes)

Missing from metadata: 191
{'dish_1561662926', 'dish_1562007817', 'dish_1562097673', 'dish_1562097001', 'dish_1562872498', 'dish_1560456348', 'dish_1561666897', 'dish_1560456370', 'dish_1562702469', 'dish_1561491210', 'dish_1561060703', 'dish_1560367333', 'dish_1562700593', 'dish_1562611680', 'dish_1561662562', 'dish_1562008517', 'dish_1560453412', 'dish_1562613403', 'dish_1560455442', 'dish_1562007904', 'dish_1561405411', 'dish_1561576767', 'dish_1562614980', 'dish_1561579845', 'dish_1560798928', 'dish_1561148021', 'dish_1562007866', 'dish_1563217804', 'dish_1562872746', 'dish_1562615388', 'dish_1561579867', 'dish_1562615360', 'dish_1560888930', 'dish_1562788601', 'dish_1563302447', 'dish_1562788816', 'dish_1560453174', 'dish_1560368506', 'dish_1561752563', 'dish_1562961650', 'dish_1560802149', 'dish_1560798960', 'dish_1561662948', 'dish_1561061687', 'dish_1561407312', 'dish_1560369294', 'dish_1561577219', 'dish_1561579706', 'dish_1560366460', 'dish_1562010440', 'dish_1561574479', 'dish_1561575033', 'dish_1562099134', 'dish_1562700957', 'dish_1562008813', 'dish_1560455421', 'dish_1562099157', 'dish_1562010929', 'dish_1563217993', 'dish_1560453328', 'dish_1560453380', 'dish_1561663855', 'dish_1560368990', 'dish_1562959190', 'dish_1561665452', 'dish_1562094931', 'dish_1561576320', 'dish_1562010418', 'dish_1562702892', 'dish_1562617492', 'dish_1561662869', 'dish_1560889061', 'dish_1562007842', 'dish_1563221054', 'dish_1562963517', 'dish_1560367296', 'dish_1561666875', 'dish_1561576707', 'dish_1560543605', 'dish_1561578441', 'dish_1561577947', 'dish_1561575068', 'dish_1562872470', 'dish_1560801883', 'dish_1563217968', 'dish_1563221157', 'dish_1562094730', 'dish_1560369313', 'dish_1562876732', 'dish_1561753477', 'dish_1561749061', 'dish_1561062237', 'dish_1562963704', 'dish_1561405912', 'dish_1561062286', 'dish_1561492228', 'dish_1562789328', 'dish_1561666923', 'dish_1562876756', 'dish_1561579933', 'dish_1562959570', 'dish_1561060642', 'dish_1561405934', 'dish_1560368570', 'dish_1563222850', 'dish_1562009182', 'dish_1562788794', 'dish_1562958809', 'dish_1560543755', 'dish_1561663914', 'dish_1559244649', 'dish_1562613974', 'dish_1562790855', 'dish_1562959547', 'dish_1560455263', 'dish_1562008549', 'dish_1562959599', 'dish_1562785369', 'dish_1561578417', 'dish_1562959799', 'dish_1561148481', 'dish_1561664013', 'dish_1560801041', 'dish_1562702132', 'dish_1561580406', 'dish_1560543625', 'dish_1560526552', 'dish_1561663891', 'dish_1562614952', 'dish_1561407283', 'dish_1563218031', 'dish_1560453356', 'dish_1562008842', 'dish_1560974009', 'dish_1561579673', 'dish_1561060613', 'dish_1560369403', 'dish_1562873028', 'dish_1561148042', 'dish_1560456326', 'dish_1562180157', 'dish_1563221086', 'dish_1561574623', 'dish_1561576794', 'dish_1562875320', 'dish_1561580431', 'dish_1562613376', 'dish_1561576074', 'dish_1562787817', 'dish_1560887480', 'dish_1562096608', 'dish_1560541760', 'dish_1562615128', 'dish_1562700568', 'dish_1561405034', 'dish_1562010394', 'dish_1561576051', 'dish_1562010865', 'dish_1561664042', 'dish_1561574848', 'dish_1561062320', 'dish_1563217939', 'dish_1561576737', 'dish_1561576978', 'dish_1562096973', 'dish_1562787848', 'dish_1562873838', 'dish_1561578461', 'dish_1560541793', 'dish_1559593794', 'dish_1559933834', 'dish_1561665065', 'dish_1561664061', 'dish_1560455399', 'dish_1560369008', 'dish_1561579902', 'dish_1562788845', 'dish_1561061123', 'dish_1562010891', 'dish_1562096633', 'dish_1560369421', 'dish_1563221640', 'dish_1561405008', 'dish_1560369146', 'dish_1561576954', 'dish_1561405389', 'dish_1563222830', 'dish_1561576680', 'dish_1560454562', 'dish_1561578394', 'dish_1562615153'}

In [ ]:
print("Sample downloaded IDs:", list(downloaded_dish_ids)[:10])
print("Sample metadata IDs:", list(dish_level['dish_id'])[:10])

Sample downloaded IDs: ['dish_1561662926', 'dish_1561666619', 'dish_1558031019', 'dish_1559848857', 'dish_1562703408', 'dish_1562774346', 'dish_1558721757', 'dish_1561575300', 'dish_1559849537', 'dish_1558461760']
Sample metadata IDs: ['dish_1561662216', 'dish_1562688426', 'dish_1561662054', 'dish_1562008979', 'dish_1560455030', 'dish_1558372433', 'dish_1563379132', 'dish_1565640549', 'dish_1563207364', 'dish_1561575474']

In [ ]:
# Strip and convert to string to be safe
dish_level['dish_id'] = dish_level['dish_id'].astype(str).str.strip()
downloaded_dish_ids = set([str(d).strip() for d in downloaded_dish_ids])

# Now check missing dishes again
missing_dishes = downloaded_dish_ids - set(dish_level['dish_id'])
print("Missing from metadata:", len(missing_dishes))
print(missing_dishes)

Missing from metadata: 191
{'dish_1561662926', 'dish_1562007817', 'dish_1562097673', 'dish_1562097001', 'dish_1562872498', 'dish_1560456348', 'dish_1561666897', 'dish_1560456370', 'dish_1562702469', 'dish_1561491210', 'dish_1561060703', 'dish_1560367333', 'dish_1562700593', 'dish_1562611680', 'dish_1561662562', 'dish_1562008517', 'dish_1560453412', 'dish_1562613403', 'dish_1560455442', 'dish_1562007904', 'dish_1561405411', 'dish_1561576767', 'dish_1562614980', 'dish_1561579845', 'dish_1560798928', 'dish_1561148021', 'dish_1562007866', 'dish_1563217804', 'dish_1562872746', 'dish_1562615388', 'dish_1561579867', 'dish_1562615360', 'dish_1560888930', 'dish_1562788601', 'dish_1563302447', 'dish_1562788816', 'dish_1560453174', 'dish_1560368506', 'dish_1561752563', 'dish_1562961650', 'dish_1560802149', 'dish_1560798960', 'dish_1561662948', 'dish_1561061687', 'dish_1561407312', 'dish_1560369294', 'dish_1561577219', 'dish_1561579706', 'dish_1560366460', 'dish_1562010440', 'dish_1561574479', 'dish_1561575033', 'dish_1562099134', 'dish_1562700957', 'dish_1562008813', 'dish_1560455421', 'dish_1562099157', 'dish_1562010929', 'dish_1563217993', 'dish_1560453328', 'dish_1560453380', 'dish_1561663855', 'dish_1560368990', 'dish_1562959190', 'dish_1561665452', 'dish_1562094931', 'dish_1561576320', 'dish_1562010418', 'dish_1562702892', 'dish_1562617492', 'dish_1561662869', 'dish_1560889061', 'dish_1562007842', 'dish_1563221054', 'dish_1562963517', 'dish_1560367296', 'dish_1561666875', 'dish_1561576707', 'dish_1560543605', 'dish_1561578441', 'dish_1561577947', 'dish_1561575068', 'dish_1562872470', 'dish_1560801883', 'dish_1563217968', 'dish_1563221157', 'dish_1562094730', 'dish_1560369313', 'dish_1562876732', 'dish_1561753477', 'dish_1561749061', 'dish_1561062237', 'dish_1562963704', 'dish_1561405912', 'dish_1561062286', 'dish_1561492228', 'dish_1562789328', 'dish_1561666923', 'dish_1562876756', 'dish_1561579933', 'dish_1562959570', 'dish_1561060642', 'dish_1561405934', 'dish_1560368570', 'dish_1563222850', 'dish_1562009182', 'dish_1562788794', 'dish_1562958809', 'dish_1560543755', 'dish_1561663914', 'dish_1559244649', 'dish_1562613974', 'dish_1562790855', 'dish_1562959547', 'dish_1560455263', 'dish_1562008549', 'dish_1562959599', 'dish_1562785369', 'dish_1561578417', 'dish_1562959799', 'dish_1561148481', 'dish_1561664013', 'dish_1560801041', 'dish_1562702132', 'dish_1561580406', 'dish_1560543625', 'dish_1560526552', 'dish_1561663891', 'dish_1562614952', 'dish_1561407283', 'dish_1563218031', 'dish_1560453356', 'dish_1562008842', 'dish_1560974009', 'dish_1561579673', 'dish_1561060613', 'dish_1560369403', 'dish_1562873028', 'dish_1561148042', 'dish_1560456326', 'dish_1562180157', 'dish_1563221086', 'dish_1561574623', 'dish_1561576794', 'dish_1562875320', 'dish_1561580431', 'dish_1562613376', 'dish_1561576074', 'dish_1562787817', 'dish_1560887480', 'dish_1562096608', 'dish_1560541760', 'dish_1562615128', 'dish_1562700568', 'dish_1561405034', 'dish_1562010394', 'dish_1561576051', 'dish_1562010865', 'dish_1561664042', 'dish_1561574848', 'dish_1561062320', 'dish_1563217939', 'dish_1561576737', 'dish_1561576978', 'dish_1562096973', 'dish_1562787848', 'dish_1562873838', 'dish_1561578461', 'dish_1560541793', 'dish_1559593794', 'dish_1559933834', 'dish_1561665065', 'dish_1561664061', 'dish_1560455399', 'dish_1560369008', 'dish_1561579902', 'dish_1562788845', 'dish_1561061123', 'dish_1562010891', 'dish_1562096633', 'dish_1560369421', 'dish_1563221640', 'dish_1561405008', 'dish_1560369146', 'dish_1561576954', 'dish_1561405389', 'dish_1563222830', 'dish_1561576680', 'dish_1560454562', 'dish_1561578394', 'dish_1562615153'}

In [ ]:
print(dish_level[dish_level['dish_id'] == 'dish_1561662926'])

Empty DataFrame
Columns: [dish_id, total_calories, total_mass, total_fat, total_carb, total_protein]
Index: []

In [ ]:
import pandas as pd

# Load the raw CSV without skipping bad lines
# This may throw errors if there are malformed rows, but we want to see all rows
try:
    raw_meta1 = pd.read_csv("/content/dish_metadata_cafe1.csv", on_bad_lines='warn')
except Exception as e:
    print("Error loading CSV:", e)

# Check if the dish_id exists in the raw dataframe
dish_id_to_check = 'dish_1561662926'

# Filter rows matching the dish_id
found_rows = raw_meta1[raw_meta1.iloc[:, 0] == dish_id_to_check]

print(f"Found rows for {dish_id_to_check}:")
print(found_rows)
print(f"Number of rows found: {len(found_rows)}")

Found rows for dish_1561662926:
Empty DataFrame
Columns: [dish_1561662216, 300.794281, 193.000000, 12.387489, 28.218290, 18.633970, ingr_0000000508, soy sauce, 3.398568, 1.80124104, 0.020391408, 0.166529832, 0.275284008, ingr_0000000122, garlic, 2.124105, 3.16491645, 0.010620525, 0.70095465, 0.13594272, ingr_0000000026, white rice, 8.496420, 11.045346, 0.02548926, 2.3789976, 0.22940334, ingr_0000000524, parsley, 0.213397, 0.079170287, 0.001707176, 0.013657408, 0.006188513, ingr_0000000094, onions, 1.707173, 0.6828692, 0.001707173, 0.15364557, 0.018778903, ingr_0000000023, brown rice, 68.000000, 75.48, 0.612, 15.64, 1.768, ingr_0000000189, vinegar, 0.853586, 0.0, 0.0.1, 0.0.2, 0.0.3, ingr_0000000054, apple, 4.267931, 2.21932412, 0.008535862, 0.59751034, 0.012803793, ingr_0000000029, mixed greens, 21.339657, 5.97510396, 0.085358628, 1.131001821, 0.469472454, ingr_0000000328, sugar, 6.372315, 24.7245822, 0.0.4, 6.372315.1, 0.0.5, ingr_0000000291, salt, 0.531519, 0.0.6, 0.0.7, 0.0.8, 0.0.9, ingr_0000000520, lemon juice, 0.853586.1, 0.14510962, 0.0.10, 0.047800816, 0.003414344, ingr_0000000161, olive oil, 3.243628, 28.67367152, 3.243628.1, 0.0.11, 0.0.12, ingr_0000000462, pork, 59.474941, ...]
Index: []

[0 rows x 125 columns]
Number of rows found: 0

/tmp/ipython-input-3621564182.py:6: ParserWarning: Skipping line 21: expected 125 fields, saw 188
Skipping line 24: expected 125 fields, saw 139
Skipping line 27: expected 125 fields, saw 132
Skipping line 31: expected 125 fields, saw 160
Skipping line 35: expected 125 fields, saw 146
Skipping line 40: expected 125 fields, saw 139
Skipping line 60: expected 125 fields, saw 188
Skipping line 93: expected 125 fields, saw 132
Skipping line 117: expected 125 fields, saw 139
Skipping line 119: expected 125 fields, saw 132
Skipping line 135: expected 125 fields, saw 181
Skipping line 148: expected 125 fields, saw 132
Skipping line 155: expected 125 fields, saw 139
Skipping line 165: expected 125 fields, saw 146
Skipping line 206: expected 125 fields, saw 181
Skipping line 215: expected 125 fields, saw 195
Skipping line 226: expected 125 fields, saw 132
Skipping line 233: expected 125 fields, saw 153
Skipping line 237: expected 125 fields, saw 153
Skipping line 275: expected 125 fields, saw 139
Skipping line 279: expected 125 fields, saw 202
Skipping line 301: expected 125 fields, saw 132
Skipping line 316: expected 125 fields, saw 132
Skipping line 358: expected 125 fields, saw 188
Skipping line 433: expected 125 fields, saw 202
Skipping line 434: expected 125 fields, saw 174
Skipping line 460: expected 125 fields, saw 139
Skipping line 494: expected 125 fields, saw 146
Skipping line 500: expected 125 fields, saw 139
Skipping line 501: expected 125 fields, saw 139
Skipping line 504: expected 125 fields, saw 139
Skipping line 505: expected 125 fields, saw 209
Skipping line 521: expected 125 fields, saw 132
Skipping line 531: expected 125 fields, saw 174
Skipping line 543: expected 125 fields, saw 132
Skipping line 545: expected 125 fields, saw 132
Skipping line 570: expected 125 fields, saw 174
Skipping line 571: expected 125 fields, saw 139
Skipping line 582: expected 125 fields, saw 146
Skipping line 588: expected 125 fields, saw 195
Skipping line 603: expected 125 fields, saw 139
Skipping line 606: expected 125 fields, saw 153
Skipping line 612: expected 125 fields, saw 167
Skipping line 613: expected 125 fields, saw 139
Skipping line 617: expected 125 fields, saw 132
Skipping line 618: expected 125 fields, saw 167
Skipping line 627: expected 125 fields, saw 139
Skipping line 644: expected 125 fields, saw 181
Skipping line 651: expected 125 fields, saw 202
Skipping line 654: expected 125 fields, saw 216
Skipping line 672: expected 125 fields, saw 167
Skipping line 675: expected 125 fields, saw 132
Skipping line 682: expected 125 fields, saw 139
Skipping line 693: expected 125 fields, saw 139
Skipping line 695: expected 125 fields, saw 132
Skipping line 697: expected 125 fields, saw 146
Skipping line 700: expected 125 fields, saw 153
Skipping line 707: expected 125 fields, saw 153
Skipping line 718: expected 125 fields, saw 139
Skipping line 727: expected 125 fields, saw 132
Skipping line 732: expected 125 fields, saw 132
Skipping line 745: expected 125 fields, saw 153
Skipping line 754: expected 125 fields, saw 174
Skipping line 761: expected 125 fields, saw 139
Skipping line 771: expected 125 fields, saw 132
Skipping line 781: expected 125 fields, saw 132
Skipping line 819: expected 125 fields, saw 132
Skipping line 825: expected 125 fields, saw 132
Skipping line 833: expected 125 fields, saw 167
Skipping line 835: expected 125 fields, saw 132
Skipping line 840: expected 125 fields, saw 132
Skipping line 847: expected 125 fields, saw 132
Skipping line 853: expected 125 fields, saw 174
Skipping line 874: expected 125 fields, saw 167
Skipping line 885: expected 125 fields, saw 139
Skipping line 917: expected 125 fields, saw 153
Skipping line 920: expected 125 fields, saw 132
Skipping line 955: expected 125 fields, saw 139
Skipping line 957: expected 125 fields, saw 146
Skipping line 961: expected 125 fields, saw 146
Skipping line 964: expected 125 fields, saw 160
Skipping line 986: expected 125 fields, saw 139
Skipping line 987: expected 125 fields, saw 153
Skipping line 1003: expected 125 fields, saw 139
Skipping line 1017: expected 125 fields, saw 202
Skipping line 1037: expected 125 fields, saw 153
Skipping line 1083: expected 125 fields, saw 153
Skipping line 1086: expected 125 fields, saw 132
Skipping line 1087: expected 125 fields, saw 167
Skipping line 1099: expected 125 fields, saw 244
Skipping line 1100: expected 125 fields, saw 146
Skipping line 1113: expected 125 fields, saw 188
Skipping line 1117: expected 125 fields, saw 160
Skipping line 1121: expected 125 fields, saw 132
Skipping line 1163: expected 125 fields, saw 146
Skipping line 1167: expected 125 fields, saw 153
Skipping line 1182: expected 125 fields, saw 132
Skipping line 1217: expected 125 fields, saw 160
Skipping line 1230: expected 125 fields, saw 132
Skipping line 1249: expected 125 fields, saw 139
Skipping line 1251: expected 125 fields, saw 202
Skipping line 1254: expected 125 fields, saw 167
Skipping line 1285: expected 125 fields, saw 132
Skipping line 1286: expected 125 fields, saw 153
Skipping line 1337: expected 125 fields, saw 188
Skipping line 1382: expected 125 fields, saw 146
Skipping line 1397: expected 125 fields, saw 132
Skipping line 1402: expected 125 fields, saw 132
Skipping line 1415: expected 125 fields, saw 230
Skipping line 1421: expected 125 fields, saw 132
Skipping line 1457: expected 125 fields, saw 160
Skipping line 1469: expected 125 fields, saw 132
Skipping line 1482: expected 125 fields, saw 146
Skipping line 1511: expected 125 fields, saw 153
Skipping line 1544: expected 125 fields, saw 167
Skipping line 1561: expected 125 fields, saw 139
Skipping line 1571: expected 125 fields, saw 181
Skipping line 1574: expected 125 fields, saw 139
Skipping line 1576: expected 125 fields, saw 188
Skipping line 1593: expected 125 fields, saw 174
Skipping line 1597: expected 125 fields, saw 167
Skipping line 1598: expected 125 fields, saw 146
Skipping line 1604: expected 125 fields, saw 132
Skipping line 1622: expected 125 fields, saw 153
Skipping line 1634: expected 125 fields, saw 174
Skipping line 1656: expected 125 fields, saw 153
Skipping line 1658: expected 125 fields, saw 167
Skipping line 1660: expected 125 fields, saw 139
Skipping line 1685: expected 125 fields, saw 160
Skipping line 1686: expected 125 fields, saw 181
Skipping line 1692: expected 125 fields, saw 139
Skipping line 1708: expected 125 fields, saw 153
Skipping line 1709: expected 125 fields, saw 160
Skipping line 1727: expected 125 fields, saw 167
Skipping line 1738: expected 125 fields, saw 174
Skipping line 1746: expected 125 fields, saw 153
Skipping line 1767: expected 125 fields, saw 160
Skipping line 1771: expected 125 fields, saw 146
Skipping line 1779: expected 125 fields, saw 139
Skipping line 1786: expected 125 fields, saw 174
Skipping line 1802: expected 125 fields, saw 132
Skipping line 1811: expected 125 fields, saw 132
Skipping line 1839: expected 125 fields, saw 153
Skipping line 1845: expected 125 fields, saw 160
Skipping line 1848: expected 125 fields, saw 146
Skipping line 1849: expected 125 fields, saw 153
Skipping line 1850: expected 125 fields, saw 153
Skipping line 1853: expected 125 fields, saw 139
Skipping line 1854: expected 125 fields, saw 209
Skipping line 1855: expected 125 fields, saw 188
Skipping line 1857: expected 125 fields, saw 181
Skipping line 1862: expected 125 fields, saw 139
Skipping line 1867: expected 125 fields, saw 139
Skipping line 1869: expected 125 fields, saw 132
Skipping line 1885: expected 125 fields, saw 139
Skipping line 1918: expected 125 fields, saw 153
Skipping line 1922: expected 125 fields, saw 139
Skipping line 1931: expected 125 fields, saw 188
Skipping line 1941: expected 125 fields, saw 139
Skipping line 1956: expected 125 fields, saw 181
Skipping line 1984: expected 125 fields, saw 132
Skipping line 1985: expected 125 fields, saw 167
Skipping line 1988: expected 125 fields, saw 132
Skipping line 2002: expected 125 fields, saw 160
Skipping line 2003: expected 125 fields, saw 139
Skipping line 2015: expected 125 fields, saw 139
Skipping line 2027: expected 125 fields, saw 216
Skipping line 2049: expected 125 fields, saw 132
Skipping line 2052: expected 125 fields, saw 132
Skipping line 2064: expected 125 fields, saw 132
Skipping line 2067: expected 125 fields, saw 132
Skipping line 2089: expected 125 fields, saw 146
Skipping line 2109: expected 125 fields, saw 146
Skipping line 2117: expected 125 fields, saw 139
Skipping line 2144: expected 125 fields, saw 139
Skipping line 2150: expected 125 fields, saw 181
Skipping line 2157: expected 125 fields, saw 146
Skipping line 2172: expected 125 fields, saw 181
Skipping line 2195: expected 125 fields, saw 188
Skipping line 2202: expected 125 fields, saw 160
Skipping line 2235: expected 125 fields, saw 167
Skipping line 2239: expected 125 fields, saw 153
Skipping line 2246: expected 125 fields, saw 160
Skipping line 2256: expected 125 fields, saw 146
Skipping line 2257: expected 125 fields, saw 195
Skipping line 2265: expected 125 fields, saw 153
Skipping line 2271: expected 125 fields, saw 132
Skipping line 2278: expected 125 fields, saw 160
Skipping line 2294: expected 125 fields, saw 202
Skipping line 2314: expected 125 fields, saw 146
Skipping line 2316: expected 125 fields, saw 153
Skipping line 2319: expected 125 fields, saw 146
Skipping line 2331: expected 125 fields, saw 167
Skipping line 2345: expected 125 fields, saw 139
Skipping line 2347: expected 125 fields, saw 153
Skipping line 2364: expected 125 fields, saw 174
Skipping line 2368: expected 125 fields, saw 202
Skipping line 2370: expected 125 fields, saw 167
Skipping line 2373: expected 125 fields, saw 132
Skipping line 2377: expected 125 fields, saw 188
Skipping line 2389: expected 125 fields, saw 223
Skipping line 2392: expected 125 fields, saw 167
Skipping line 2418: expected 125 fields, saw 132
Skipping line 2428: expected 125 fields, saw 167
Skipping line 2459: expected 125 fields, saw 139
Skipping line 2468: expected 125 fields, saw 139
Skipping line 2497: expected 125 fields, saw 146
Skipping line 2498: expected 125 fields, saw 153
Skipping line 2522: expected 125 fields, saw 160
Skipping line 2523: expected 125 fields, saw 139
Skipping line 2524: expected 125 fields, saw 188
Skipping line 2543: expected 125 fields, saw 132
Skipping line 2556: expected 125 fields, saw 132
Skipping line 2593: expected 125 fields, saw 132
Skipping line 2594: expected 125 fields, saw 167
Skipping line 2616: expected 125 fields, saw 181
Skipping line 2620: expected 125 fields, saw 195
Skipping line 2642: expected 125 fields, saw 174
Skipping line 2660: expected 125 fields, saw 139
Skipping line 2671: expected 125 fields, saw 139
Skipping line 2697: expected 125 fields, saw 153
Skipping line 2699: expected 125 fields, saw 132
Skipping line 2749: expected 125 fields, saw 132
Skipping line 2750: expected 125 fields, saw 146
Skipping line 2755: expected 125 fields, saw 132
Skipping line 2759: expected 125 fields, saw 132
Skipping line 2763: expected 125 fields, saw 139
Skipping line 2766: expected 125 fields, saw 146
Skipping line 2768: expected 125 fields, saw 160
Skipping line 2770: expected 125 fields, saw 146
Skipping line 2790: expected 125 fields, saw 132
Skipping line 2813: expected 125 fields, saw 146
Skipping line 2836: expected 125 fields, saw 160
Skipping line 2838: expected 125 fields, saw 146
Skipping line 2840: expected 125 fields, saw 167
Skipping line 2849: expected 125 fields, saw 146
Skipping line 2853: expected 125 fields, saw 216
Skipping line 2867: expected 125 fields, saw 153
Skipping line 2868: expected 125 fields, saw 132
Skipping line 2875: expected 125 fields, saw 146
Skipping line 2882: expected 125 fields, saw 195
Skipping line 2884: expected 125 fields, saw 153
Skipping line 2896: expected 125 fields, saw 139
Skipping line 2937: expected 125 fields, saw 188
Skipping line 2944: expected 125 fields, saw 132
Skipping line 2948: expected 125 fields, saw 146
Skipping line 2954: expected 125 fields, saw 230
Skipping line 2961: expected 125 fields, saw 139
Skipping line 2981: expected 125 fields, saw 174
Skipping line 2999: expected 125 fields, saw 139
Skipping line 3026: expected 125 fields, saw 146
Skipping line 3040: expected 125 fields, saw 174
Skipping line 3042: expected 125 fields, saw 146
Skipping line 3045: expected 125 fields, saw 139
Skipping line 3067: expected 125 fields, saw 146
Skipping line 3075: expected 125 fields, saw 153
Skipping line 3129: expected 125 fields, saw 244
Skipping line 3142: expected 125 fields, saw 139
Skipping line 3145: expected 125 fields, saw 132
Skipping line 3153: expected 125 fields, saw 139
Skipping line 3156: expected 125 fields, saw 160
Skipping line 3204: expected 125 fields, saw 132
Skipping line 3221: expected 125 fields, saw 153
Skipping line 3240: expected 125 fields, saw 160
Skipping line 3254: expected 125 fields, saw 132
Skipping line 3293: expected 125 fields, saw 139
Skipping line 3297: expected 125 fields, saw 174
Skipping line 3306: expected 125 fields, saw 160
Skipping line 3328: expected 125 fields, saw 132
Skipping line 3334: expected 125 fields, saw 167
Skipping line 3353: expected 125 fields, saw 195
Skipping line 3370: expected 125 fields, saw 153
Skipping line 3381: expected 125 fields, saw 167
Skipping line 3411: expected 125 fields, saw 132
Skipping line 3433: expected 125 fields, saw 139
Skipping line 3442: expected 125 fields, saw 139
Skipping line 3469: expected 125 fields, saw 202
Skipping line 3470: expected 125 fields, saw 174
Skipping line 3490: expected 125 fields, saw 146
Skipping line 3495: expected 125 fields, saw 174
Skipping line 3496: expected 125 fields, saw 139
Skipping line 3525: expected 125 fields, saw 160
Skipping line 3538: expected 125 fields, saw 132
Skipping line 3565: expected 125 fields, saw 160
Skipping line 3586: expected 125 fields, saw 181
Skipping line 3588: expected 125 fields, saw 139
Skipping line 3624: expected 125 fields, saw 188
Skipping line 3630: expected 125 fields, saw 146
Skipping line 3632: expected 125 fields, saw 160
Skipping line 3635: expected 125 fields, saw 139
Skipping line 3637: expected 125 fields, saw 132
Skipping line 3644: expected 125 fields, saw 209
Skipping line 3658: expected 125 fields, saw 181
Skipping line 3689: expected 125 fields, saw 139
Skipping line 3692: expected 125 fields, saw 153
Skipping line 3704: expected 125 fields, saw 132
Skipping line 3713: expected 125 fields, saw 132
Skipping line 3734: expected 125 fields, saw 160
Skipping line 3742: expected 125 fields, saw 167
Skipping line 3785: expected 125 fields, saw 146
Skipping line 3793: expected 125 fields, saw 132
Skipping line 3798: expected 125 fields, saw 181
Skipping line 3835: expected 125 fields, saw 132
Skipping line 3836: expected 125 fields, saw 167
Skipping line 3840: expected 125 fields, saw 139
Skipping line 3865: expected 125 fields, saw 153
Skipping line 3881: expected 125 fields, saw 167
Skipping line 3892: expected 125 fields, saw 146
Skipping line 3907: expected 125 fields, saw 153
Skipping line 3914: expected 125 fields, saw 167
Skipping line 3921: expected 125 fields, saw 132
Skipping line 3922: expected 125 fields, saw 132
Skipping line 3928: expected 125 fields, saw 146
Skipping line 3930: expected 125 fields, saw 181
Skipping line 3939: expected 125 fields, saw 181
Skipping line 3941: expected 125 fields, saw 139
Skipping line 3947: expected 125 fields, saw 139
Skipping line 3956: expected 125 fields, saw 139
Skipping line 3973: expected 125 fields, saw 146
Skipping line 3981: expected 125 fields, saw 139
Skipping line 3995: expected 125 fields, saw 153
Skipping line 4000: expected 125 fields, saw 209
Skipping line 4064: expected 125 fields, saw 167
Skipping line 4067: expected 125 fields, saw 139
Skipping line 4084: expected 125 fields, saw 167
Skipping line 4090: expected 125 fields, saw 132
Skipping line 4111: expected 125 fields, saw 153
Skipping line 4133: expected 125 fields, saw 153
Skipping line 4155: expected 125 fields, saw 209
Skipping line 4160: expected 125 fields, saw 160
Skipping line 4169: expected 125 fields, saw 188
Skipping line 4174: expected 125 fields, saw 209
Skipping line 4183: expected 125 fields, saw 146
Skipping line 4212: expected 125 fields, saw 139
Skipping line 4221: expected 125 fields, saw 132
Skipping line 4256: expected 125 fields, saw 139
Skipping line 4257: expected 125 fields, saw 146
Skipping line 4286: expected 125 fields, saw 132
Skipping line 4296: expected 125 fields, saw 160
Skipping line 4303: expected 125 fields, saw 132
Skipping line 4312: expected 125 fields, saw 153
Skipping line 4335: expected 125 fields, saw 188
Skipping line 4337: expected 125 fields, saw 167
Skipping line 4343: expected 125 fields, saw 195
Skipping line 4352: expected 125 fields, saw 132
Skipping line 4374: expected 125 fields, saw 146
Skipping line 4401: expected 125 fields, saw 132
Skipping line 4412: expected 125 fields, saw 167
Skipping line 4419: expected 125 fields, saw 160
Skipping line 4450: expected 125 fields, saw 139
Skipping line 4468: expected 125 fields, saw 167
Skipping line 4528: expected 125 fields, saw 146
Skipping line 4550: expected 125 fields, saw 153
Skipping line 4553: expected 125 fields, saw 209
Skipping line 4561: expected 125 fields, saw 139
Skipping line 4567: expected 125 fields, saw 139
Skipping line 4568: expected 125 fields, saw 174
Skipping line 4582: expected 125 fields, saw 160
Skipping line 4583: expected 125 fields, saw 230
Skipping line 4589: expected 125 fields, saw 181
Skipping line 4595: expected 125 fields, saw 146
Skipping line 4611: expected 125 fields, saw 195
Skipping line 4627: expected 125 fields, saw 202
Skipping line 4629: expected 125 fields, saw 132
Skipping line 4641: expected 125 fields, saw 167
Skipping line 4642: expected 125 fields, saw 132
Skipping line 4656: expected 125 fields, saw 153
Skipping line 4664: expected 125 fields, saw 188
Skipping line 4702: expected 125 fields, saw 139
Skipping line 4709: expected 125 fields, saw 153
Skipping line 4725: expected 125 fields, saw 153
Skipping line 4726: expected 125 fields, saw 153
Skipping line 4743: expected 125 fields, saw 139
Skipping line 4748: expected 125 fields, saw 153
Skipping line 4752: expected 125 fields, saw 146
Skipping line 4757: expected 125 fields, saw 146

  raw_meta1 = pd.read_csv("/content/dish_metadata_cafe1.csv", on_bad_lines='warn')

In [ ]:
import csv
import pandas as pd

csv_path = "/content/dish_metadata_cafe1.csv"
dish_level_rows = []

# Open CSV and read line by line
with open(csv_path, newline='', encoding='utf-8') as f:
    reader = csv.reader(f)
    for row in reader:
        if len(row) >= 6:  # Make sure at least dish-level columns exist
            dish_level_rows.append(row[:6])  # Take first 6 columns only

# Convert to DataFrame
dish_level_all = pd.DataFrame(
    dish_level_rows,
    columns=["dish_id", "total_calories", "total_mass", "total_fat", "total_carb", "total_protein"]
)

# Convert numeric columns
for col in ["total_calories", "total_mass", "total_fat", "total_carb", "total_protein"]:
    dish_level_all[col] = pd.to_numeric(dish_level_all[col], errors='coerce')

print("Total rows loaded from CSV:", len(dish_level_all))
dish_level_all.head()

Total rows loaded from CSV: 4768

,dish_id,total_calories,total_mass,total_fat,total_carb,total_protein
0,dish_1561662216,300.794281,193.0,12.387489,28.218290,18.633970
1,dish_1562688426,137.569992,88.0,8.256000,5.190000,10.297000
2,dish_1561662054,419.438782,292.0,23.838249,26.351543,25.910593
3,dish_1562008979,382.936646,290.0,22.224644,10.173570,35.345387
4,dish_1560455030,20.590000,103.0,0.148000,4.625000,0.956000

In [ ]:
filtered_metadata = dish_level_all[dish_level_all['dish_id'].isin(downloaded_dish_ids)]
print("Rows after filtering:", len(filtered_metadata))
filtered_metadata.to_csv("/content/nutrition5k_subset/labels_subset.csv", index=False)

Rows after filtering: 2000

In [ ]:
from PIL import Image
import os

IMAGE_DIR = "/content/nutrition5k_subset/images"
RESIZE_DIR = "/content/nutrition5k_subset/images_resized"
os.makedirs(RESIZE_DIR, exist_ok=True)

for file in os.listdir(IMAGE_DIR):
    if file.endswith(".png") or file.endswith(".jpg"):
        img_path = os.path.join(IMAGE_DIR, file)
        img = Image.open(img_path).convert("RGB")
        img = img.resize((224, 224))
        img.save(os.path.join(RESIZE_DIR, file))

print("All images resized and saved to images_resized/")

All images resized and saved to images_resized/

In [ ]:
from google.colab import drive
import os

# Mount your Google Drive
drive.mount('/content/drive')

# Create a folder in Drive to save resized images
DRIVE_RESIZE_DIR = '/content/drive/MyDrive/nutrition5k_resized'
os.makedirs(DRIVE_RESIZE_DIR, exist_ok=True)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
from google.colab import drive
import os
from shutil import copy2

# 1️⃣ Mount Google Drive
drive.mount('/content/drive')

# 2️⃣ Path to local resized images
LOCAL_RESIZE_DIR = "/content/nutrition5k_subset/images_resized"

# 3️⃣ Path in Google Drive where you want to save
DRIVE_RESIZE_DIR = "/content/drive/MyDrive/nutrition5k_resized"
os.makedirs(DRIVE_RESIZE_DIR, exist_ok=True)

# 4️⃣ Copy all resized images to Drive
for file in os.listdir(LOCAL_RESIZE_DIR):
    if file.endswith(".png") or file.endswith(".jpg"):
        copy2(os.path.join(LOCAL_RESIZE_DIR, file), DRIVE_RESIZE_DIR)

print(f"All resized images copied to Google Drive: {DRIVE_RESIZE_DIR}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
All resized images copied to Google Drive: /content/drive/MyDrive/nutrition5k_resized

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
import pandas as pd
import numpy as np
from PIL import Image
from sklearn.model_selection import train_test_split
import torch
from torch import nn, optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models

# Paths
CSV_FILE = "/content/labels_subset.csv"      # Your filtered labels CSV
IMG_DIR = "/content/drive/MyDrive/nutrition5k_resized"          # Resized images folder

# Device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Dataset class
class NutritionDataset(Dataset):
    def __init__(self, csv_file, img_dir, transform=None):
        self.data = pd.read_csv(csv_file)
        self.img_dir = img_dir
        self.transform = transform
        self.labels = self.data[['total_calories', 'total_fat', 'total_carb', 'total_protein']].values
        self.filenames = self.data['dish_id'].values

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        img_name = self.filenames[idx] + "_rgb.png"
        img_path = os.path.join(self.img_dir, img_name)
        image = Image.open(img_path).convert('RGB')

        if self.transform:
            image = self.transform(image)

        label = torch.tensor(self.labels[idx], dtype=torch.float32)
        return image, label, self.filenames[idx]

# Transformations
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

# Load dataset
dataset = NutritionDataset(CSV_FILE, IMG_DIR, transform=transform)

# Train-test split (80%-20%)
train_size = int(0.8 * len(dataset))
test_size = len(dataset) - train_size
train_dataset, test_dataset = torch.utils.data.random_split(dataset, [train_size, test_size])

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

# Model - Pretrained ResNet50 with output layer for 4 nutrition values
model = models.resnet50(pretrained=True)
num_ftrs = model.fc.in_features
model.fc = nn.Linear(num_ftrs, 4)
model = model.to(device)

# Loss and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training function
def train_model(model, dataloader, criterion, optimizer, epochs=10):
    model.train()
    for epoch in range(epochs):
        running_loss = 0.0
        for inputs, labels, _ in dataloader:
            inputs, labels = inputs.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            running_loss += loss.item() * inputs.size(0)

        epoch_loss = running_loss / len(dataloader.dataset)
        print(f"Epoch {epoch+1}/{epochs}, Loss: {epoch_loss:.4f}")

# Evaluation function
def evaluate_model(model, dataloader, criterion):
    model.eval()
    running_loss = 0.0
    with torch.no_grad():
        for inputs, labels, _ in dataloader:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            running_loss += loss.item() * inputs.size(0)

    total_loss = running_loss / len(dataloader.dataset)
    print(f"Test Loss (MSE): {total_loss:.4f}")

# Train the model
train_model(model, train_loader, criterion, optimizer, epochs=10)

# Evaluate the model
evaluate_model(model, test_loader, criterion)

# Predict a single image (example)
def predict_single_image(model, img_filename):
    model.eval()
    img_path = os.path.join(IMG_DIR, img_filename)
    image = Image.open(img_path).convert("RGB")
    image = transform(image).unsqueeze(0).to(device)

    with torch.no_grad():
        pred = model(image)
    pred_np = np.round(pred.cpu().numpy(), 2)[0]

    dish_id = img_filename.replace("_rgb.png", "")
    print(f"Prediction for {dish_id}:")
    print(f"  Calories: {pred_np[0]}")
    print(f"  Fat:      {pred_np[1]}")
    print(f"  Carbs:    {pred_np[2]}")
    print(f"  Protein:  {pred_np[3]}")

# Example prediction
predict_single_image(model, "dish_1556572657_rgb.png")

/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)

In [2]:
import pandas as pd
df = pd.read_csv("/content/labels_subset.csv")
print(df.columns.tolist())
print(df.head(2))

['dish_id', 'total_calories', 'total_mass', 'total_fat', 'total_carb', 'total_protein']
           dish_id  total_calories  total_mass  total_fat  total_carb  \
0  dish_1561662216      300.794281       193.0  12.387489   28.218290
1  dish_1561662054      419.438782       292.0  23.838249   26.351543

   total_protein
0      18.633970
1      25.910593

In [ ]:
import os
import pandas as pd
import numpy as np
from PIL import Image
import torch
from torch import nn, optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Paths
CSV_FILE = "/content/labels_subset.csv"
IMG_DIR = "/content/drive/MyDrive/nutrition5k_resized"

# Device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device, flush=True)

# Dataset class
class NutritionDataset(Dataset):
    def __init__(self, csv_file, img_dir, transform=None):
        self.data = pd.read_csv(csv_file)
        self.img_dir = img_dir
        self.transform = transform
        self.labels = self.data[['total_calories', 'total_fat', 'total_carb', 'total_protein']].values
        self.filenames = self.data['dish_id'].values

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        img_name = self.filenames[idx] + "_rgb.png"
        img_path = os.path.join(self.img_dir, img_name)
        image = Image.open(img_path).convert('RGB')
        if self.transform:
            image = self.transform(image)
        label = torch.tensor(self.labels[idx], dtype=torch.float32)
        return image, label, self.filenames[idx]

# Transformations
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

# Load dataset
dataset = NutritionDataset(CSV_FILE, IMG_DIR, transform=transform)
print(f"Dataset size: {len(dataset)}", flush=True)
sample_img, sample_label, sample_id = dataset[0]
print(f"Sample loaded: {sample_id}, label: {sample_label}", flush=True)

# Train-test split
train_size = int(0.8 * len(dataset))
test_size = len(dataset) - train_size
train_dataset, test_dataset = torch.utils.data.random_split(dataset, [train_size, test_size])
print(f"Train size: {train_size}, Test size: {test_size}", flush=True)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True, num_workers=2, pin_memory=True)
test_loader  = DataLoader(test_dataset,  batch_size=32, shuffle=False, num_workers=2, pin_memory=True)

# Model
model = models.resnet50(weights=models.ResNet50_Weights.DEFAULT)
num_ftrs = model.fc.in_features
model.fc = nn.Linear(num_ftrs, 4)
model = model.to(device)
print("Model loaded successfully!", flush=True)

# Loss and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training
def train_model(model, dataloader, criterion, optimizer, epochs=10):
    model.train()
    for epoch in range(epochs):
        running_loss = 0.0
        for i, (inputs, labels, _) in enumerate(dataloader):
            inputs, labels = inputs.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            running_loss += loss.item() * inputs.size(0)
            if i % 10 == 0:
                print(f"  Epoch {epoch+1}, Batch {i}/{len(dataloader)}", flush=True)

        epoch_loss = running_loss / len(dataloader.dataset)
        print(f"✅ Epoch {epoch+1}/{epochs}, Loss: {epoch_loss:.4f}", flush=True)

# Evaluation
def evaluate_model(model, dataloader, criterion):
    model.eval()
    running_loss = 0.0
    with torch.no_grad():
        for inputs, labels, _ in dataloader:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            running_loss += loss.item() * inputs.size(0)
    total_loss = running_loss / len(dataloader.dataset)
    print(f"✅ Test Loss (MSE): {total_loss:.4f}", flush=True)

# Predict single image
def predict_single_image(model, img_filename):
    model.eval()
    img_path = os.path.join(IMG_DIR, img_filename)
    image = Image.open(img_path).convert("RGB")
    image = transform(image).unsqueeze(0).to(device)
    with torch.no_grad():
        pred = model(image)
    pred_np = np.round(pred.cpu().numpy(), 2)[0]
    dish_id = img_filename.replace("_rgb.png", "")
    print(f"\nPrediction for {dish_id}:")
    print(f"  Calories: {pred_np[0]}")
    print(f"  Fat:      {pred_np[1]}")
    print(f"  Carbs:    {pred_np[2]}")
    print(f"  Protein:  {pred_np[3]}")

# Run training
train_model(model, train_loader, criterion, optimizer, epochs=10)

# Run evaluation
evaluate_model(model, test_loader, criterion)

# Predict example — replace dish id with one from your CSV
predict_single_image(model, "dish_1561662216_rgb.png")

Mounted at /content/drive
Using device: cuda
Dataset size: 2000
Sample loaded: dish_1561662216, label: tensor([300.7943,  12.3875,  28.2183,  18.6340])
Train size: 1600, Test size: 400
Downloading: "https://download.pytorch.org/models/resnet50-11ad3fa6.pth" to /root/.cache/torch/hub/checkpoints/resnet50-11ad3fa6.pth

100%|██████████| 97.8M/97.8M [00:00<00:00, 188MB/s]

Model loaded successfully!
  Epoch 1, Batch 0/50
  Epoch 1, Batch 10/50
  Epoch 1, Batch 20/50
  Epoch 1, Batch 30/50
  Epoch 1, Batch 40/50
✅ Epoch 1/10, Loss: 15030.5038
  Epoch 2, Batch 0/50
  Epoch 2, Batch 10/50
  Epoch 2, Batch 20/50
  Epoch 2, Batch 30/50
  Epoch 2, Batch 40/50
✅ Epoch 2/10, Loss: 6319.7848
  Epoch 3, Batch 0/50
  Epoch 3, Batch 10/50
  Epoch 3, Batch 20/50
  Epoch 3, Batch 30/50
  Epoch 3, Batch 40/50
✅ Epoch 3/10, Loss: 4921.3701
  Epoch 4, Batch 0/50
  Epoch 4, Batch 10/50
  Epoch 4, Batch 20/50
  Epoch 4, Batch 30/50
  Epoch 4, Batch 40/50
✅ Epoch 4/10, Loss: 3747.9232
  Epoch 5, Batch 0/50
  Epoch 5, Batch 10/50
  Epoch 5, Batch 20/50
  Epoch 5, Batch 30/50
  Epoch 5, Batch 40/50
✅ Epoch 5/10, Loss: 3741.8863
  Epoch 6, Batch 0/50
  Epoch 6, Batch 10/50
  Epoch 6, Batch 20/50
  Epoch 6, Batch 30/50
  Epoch 6, Batch 40/50
✅ Epoch 6/10, Loss: 4090.7559
  Epoch 7, Batch 0/50

In [4]:
import os
import pandas as pd
import numpy as np
from PIL import Image
import torch
from torch import nn, optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Paths
CSV_FILE = "/content/labels_subset.csv"
IMG_DIR = "/content/drive/MyDrive/nutrition5k_resized"
SAVE_DIR = "/content/drive/MyDrive/nutrition_checkpoints"

# Create save folder if it doesn't exist
os.makedirs(SAVE_DIR, exist_ok=True)

# Device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device, flush=True)

# Dataset class
class NutritionDataset(Dataset):
    def __init__(self, csv_file, img_dir, transform=None):
        self.data = pd.read_csv(csv_file)
        self.img_dir = img_dir
        self.transform = transform
        self.labels = self.data[['total_calories', 'total_fat', 'total_carb', 'total_protein']].values
        self.filenames = self.data['dish_id'].values

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        img_name = self.filenames[idx] + "_rgb.png"
        img_path = os.path.join(self.img_dir, img_name)
        image = Image.open(img_path).convert('RGB')
        if self.transform:
            image = self.transform(image)
        label = torch.tensor(self.labels[idx], dtype=torch.float32)
        return image, label, self.filenames[idx]

# Transformations
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

# Load dataset
dataset = NutritionDataset(CSV_FILE, IMG_DIR, transform=transform)
print(f"Dataset size: {len(dataset)}", flush=True)
sample_img, sample_label, sample_id = dataset[0]
print(f"Sample loaded: {sample_id}, label: {sample_label}", flush=True)

# Train-test split
train_size = int(0.8 * len(dataset))
test_size = len(dataset) - train_size
train_dataset, test_dataset = torch.utils.data.random_split(dataset, [train_size, test_size])
print(f"Train size: {train_size}, Test size: {test_size}", flush=True)

# Reduced batch size to 16 to avoid memory crash
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True, num_workers=2, pin_memory=True)
test_loader  = DataLoader(test_dataset,  batch_size=16, shuffle=False, num_workers=2, pin_memory=True)

# Model
model = models.resnet50(weights=models.ResNet50_Weights.DEFAULT)
num_ftrs = model.fc.in_features
model.fc = nn.Linear(num_ftrs, 4)
model = model.to(device)
print("Model loaded successfully!", flush=True)

# Check if a saved checkpoint exists and resume from it
checkpoint_path = None
for i in range(10, 0, -1):
    path = f"{SAVE_DIR}/nutrition_model_epoch{i}.pth"
    if os.path.exists(path):
        checkpoint_path = path
        start_epoch = i
        break

if checkpoint_path:
    model.load_state_dict(torch.load(checkpoint_path))
    print(f"✅ Resumed from saved checkpoint: epoch {start_epoch}", flush=True)
else:
    start_epoch = 0
    print("Starting fresh training", flush=True)

# Loss and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training
def train_model(model, dataloader, criterion, optimizer, total_epochs=10, start_epoch=0):
    model.train()
    for epoch in range(start_epoch, total_epochs):
        running_loss = 0.0
        for i, (inputs, labels, _) in enumerate(dataloader):
            inputs, labels = inputs.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            running_loss += loss.item() * inputs.size(0)
            if i % 10 == 0:
                print(f"  Epoch {epoch+1}, Batch {i}/{len(dataloader)}", flush=True)

        epoch_loss = running_loss / len(dataloader.dataset)
        print(f"✅ Epoch {epoch+1}/{total_epochs}, Loss: {epoch_loss:.4f}", flush=True)

        # Save after every epoch to Drive
        save_path = f"{SAVE_DIR}/nutrition_model_epoch{epoch+1}.pth"
        torch.save(model.state_dict(), save_path)
        print(f"💾 Saved: {save_path}", flush=True)

# Evaluation
def evaluate_model(model, dataloader, criterion):
    model.eval()
    running_loss = 0.0
    with torch.no_grad():
        for inputs, labels, _ in dataloader:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            running_loss += loss.item() * inputs.size(0)
    total_loss = running_loss / len(dataloader.dataset)
    print(f"✅ Test Loss (MSE): {total_loss:.4f}", flush=True)

# Predict single image
def predict_single_image(model, img_filename):
    model.eval()
    img_path = os.path.join(IMG_DIR, img_filename)
    image = Image.open(img_path).convert("RGB")
    image = transform(image).unsqueeze(0).to(device)
    with torch.no_grad():
        pred = model(image)
    pred_np = np.round(pred.cpu().numpy(), 2)[0]
    dish_id = img_filename.replace("_rgb.png", "")
    print(f"\nPrediction for {dish_id}:")
    print(f"  Calories: {pred_np[0]}")
    print(f"  Fat:      {pred_np[1]}")
    print(f"  Carbs:    {pred_np[2]}")
    print(f"  Protein:  {pred_np[3]}")

# Run training (auto resumes if checkpoint exists)
train_model(model, train_loader, criterion, optimizer, total_epochs=10, start_epoch=start_epoch)

# Evaluate
evaluate_model(model, test_loader, criterion)

# Predict example
predict_single_image(model, "dish_1561662216_rgb.png")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Using device: cuda
Dataset size: 2000
Sample loaded: dish_1561662216, label: tensor([300.7943,  12.3875,  28.2183,  18.6340])
Train size: 1600, Test size: 400
Model loaded successfully!
Starting fresh training
  Epoch 1, Batch 0/100
  Epoch 1, Batch 10/100
  Epoch 1, Batch 20/100
  Epoch 1, Batch 30/100
  Epoch 1, Batch 40/100
  Epoch 1, Batch 50/100
  Epoch 1, Batch 60/100
  Epoch 1, Batch 70/100
  Epoch 1, Batch 80/100
  Epoch 1, Batch 90/100
✅ Epoch 1/10, Loss: 11968.7950
💾 Saved: /content/drive/MyDrive/nutrition_checkpoints/nutrition_model_epoch1.pth
  Epoch 2, Batch 0/100
  Epoch 2, Batch 10/100
  Epoch 2, Batch 20/100
  Epoch 2, Batch 30/100
  Epoch 2, Batch 40/100
  Epoch 2, Batch 50/100
  Epoch 2, Batch 60/100
  Epoch 2, Batch 70/100
  Epoch 2, Batch 80/100
  Epoch 2, Batch 90/100
✅ Epoch 2/10, Loss: 5686.0927
💾 Saved: /content/drive/MyDrive/nutrition_checkpoints/nutrition_model_epoch2.pth
  Epoch 3, Batch 0/100
  Epoch 3, Batch 10/100
  Epoch 3, Batch 20/100
  Epoch 3, Batch 30/100
  Epoch 3, Batch 40/100
  Epoch 3, Batch 50/100
  Epoch 3, Batch 60/100
  Epoch 3, Batch 70/100
  Epoch 3, Batch 80/100
  Epoch 3, Batch 90/100
✅ Epoch 3/10, Loss: 5078.3748
💾 Saved: /content/drive/MyDrive/nutrition_checkpoints/nutrition_model_epoch3.pth
  Epoch 4, Batch 0/100
  Epoch 4, Batch 10/100
  Epoch 4, Batch 20/100
  Epoch 4, Batch 30/100
  Epoch 4, Batch 40/100
  Epoch 4, Batch 50/100
  Epoch 4, Batch 60/100
  Epoch 4, Batch 70/100
  Epoch 4, Batch 80/100
  Epoch 4, Batch 90/100
✅ Epoch 4/10, Loss: 5038.3090
💾 Saved: /content/drive/MyDrive/nutrition_checkpoints/nutrition_model_epoch4.pth
  Epoch 5, Batch 0/100
  Epoch 5, Batch 10/100
  Epoch 5, Batch 20/100
  Epoch 5, Batch 30/100
  Epoch 5, Batch 40/100
  Epoch 5, Batch 50/100
  Epoch 5, Batch 60/100
  Epoch 5, Batch 70/100
  Epoch 5, Batch 80/100
  Epoch 5, Batch 90/100
✅ Epoch 5/10, Loss: 4357.8713
💾 Saved: /content/drive/MyDrive/nutrition_checkpoints/nutrition_model_epoch5.pth
  Epoch 6, Batch 0/100
  Epoch 6, Batch 10/100
  Epoch 6, Batch 20/100
  Epoch 6, Batch 30/100
  Epoch 6, Batch 40/100
  Epoch 6, Batch 50/100
  Epoch 6, Batch 60/100
  Epoch 6, Batch 70/100
  Epoch 6, Batch 80/100
  Epoch 6, Batch 90/100
✅ Epoch 6/10, Loss: 3934.3082
💾 Saved: /content/drive/MyDrive/nutrition_checkpoints/nutrition_model_epoch6.pth
  Epoch 7, Batch 0/100
  Epoch 7, Batch 10/100
  Epoch 7, Batch 20/100
  Epoch 7, Batch 30/100
  Epoch 7, Batch 40/100
  Epoch 7, Batch 50/100
  Epoch 7, Batch 60/100
  Epoch 7, Batch 70/100
  Epoch 7, Batch 80/100
  Epoch 7, Batch 90/100
✅ Epoch 7/10, Loss: 3401.3717
💾 Saved: /content/drive/MyDrive/nutrition_checkpoints/nutrition_model_epoch7.pth
  Epoch 8, Batch 0/100
  Epoch 8, Batch 10/100
  Epoch 8, Batch 20/100
  Epoch 8, Batch 30/100
  Epoch 8, Batch 40/100
  Epoch 8, Batch 50/100
  Epoch 8, Batch 60/100
  Epoch 8, Batch 70/100
  Epoch 8, Batch 80/100
  Epoch 8, Batch 90/100
✅ Epoch 8/10, Loss: 3884.8048
💾 Saved: /content/drive/MyDrive/nutrition_checkpoints/nutrition_model_epoch8.pth
  Epoch 9, Batch 0/100
  Epoch 9, Batch 10/100
  Epoch 9, Batch 20/100
  Epoch 9, Batch 30/100
  Epoch 9, Batch 40/100
  Epoch 9, Batch 50/100
  Epoch 9, Batch 60/100
  Epoch 9, Batch 70/100
  Epoch 9, Batch 80/100
  Epoch 9, Batch 90/100
✅ Epoch 9/10, Loss: 3505.6256
💾 Saved: /content/drive/MyDrive/nutrition_checkpoints/nutrition_model_epoch9.pth
  Epoch 10, Batch 0/100
  Epoch 10, Batch 10/100
  Epoch 10, Batch 20/100
  Epoch 10, Batch 30/100
  Epoch 10, Batch 40/100
  Epoch 10, Batch 50/100
  Epoch 10, Batch 60/100
  Epoch 10, Batch 70/100
  Epoch 10, Batch 80/100
  Epoch 10, Batch 90/100
✅ Epoch 10/10, Loss: 3200.8184
💾 Saved: /content/drive/MyDrive/nutrition_checkpoints/nutrition_model_epoch10.pth
✅ Test Loss (MSE): 3167.9114

Prediction for dish_1561662216:
  Calories: 191.69000244140625
  Fat:      7.139999866485596
  Carbs:    15.489999771118164
  Protein:  10.59000015258789